version: "3.7"

services:
  database-postgres:
    image: postgres
    container_name: database-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=module-ts
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: modulo-ts
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database-postgres
    depends_on:
      - database-postgres

volumes:
  pgdata:
    driver: local
